### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by Ahmed3rab** [mitydigital/statamic-tinymce-cloud#1]
Hi, I keep getting this error, and have no idea why.

Here's my config json object:

`{
  "height": 500,
  "menubar": true
}
`

Here's the log message

![image](https://i.imgur.com/0o3ibq6.png)

**Comment by martyf** [comment]
Can you provide further information on your configuration within Statamic too? I cannot replicate this error - I've used your configuration string, and it runs as expected.

**Comment by Ahmed3rab** [comment]
What kind of information are you looking for exactly? I'll try to replicate the issue in another project and get back with the result

**Comment by Ahmed3rab** [comment]
I reinstalled it again and everything went well, I guess there was some kind of error with the installation, maybe? I'll close the issue for now unless this occurs again with more information about the error. Thanks @martyf

**Comment by martyf** [comment]
The Vue component itself doesn't do much except mount the Tiny-made Vue component for TinyMCE - perhaps there was an issue with the configuration? Glad its sorted though.
