### ISSUE TITLE
Add custom sets

### ISSUE THREAD

**Issue by sattyframework** [mitydigital/statamic-tinymce-cloud#14]
### Bug description

Hey there, just wondered if it is possible to add custom field sets to the tiny mce editor like you can with the bard editor? 

### Steps to reproduce

N/A

### Environment and versions

```yaml
N/A
```

**Comment by martyf** [comment]
Unfortunately no as they're very different in what they do.

Bard maintains everything as a structure (i.e. an array) where as this is plain HTML. The two aren't compatible.

If you're wanting sets, is there a reason you're not using a Bard field?

**Comment by sattyframework** [comment]
Ah no problems, I thought this would be the case but thought I'd double check. I was looking at using TinyMCE for its comments plugin.

**Comment by martyf** [comment]
Cool bananas - and yeah unfortunately very different ecosystems between the two so Sets are only in Bard.
