### ISSUE TITLE
configuration image upload

### ISSUE THREAD

**Issue by michapixel** [mitydigital/statamic-tinymce-cloud#3]
could you give an example, please?

**Comment by martyf** [comment]
Can you please be more specific? Not sure what you're asking.

**Comment by michapixel** [comment]
I want to use this / your plugin as a replacement for bard, but i need to be sure i can upload images / files with it, or at least browse the statamic's uploaded assets etc. Is this even possible (i know tiny has some docs for this, but not specifically for statamic).

**Comment by martyf** [comment]
That's a bigger concept than what this plugin was intended to do. 

TinyMCE doesn't ship with a file manager that can be run on local files - although they do have Tiny Drive, but they manage the hosting side of things.

The other option is to use a third party file manager to handle this. However this is starting to get opinionated with what file manager to use (paid options, open source options, etc) and how they fit in within your infrastructure.

Either way, there are many variables with how you have your flysystem set up with how to approach this. I don't have the capacity to write a TinyMCE 5 file manager plugin to handle the browsing of the files at this point in time, but can add it to the to-do list but don't have an ETA.

**Comment by michapixel** [comment]
Okay, i understand that.  

Another thing is, and i probably should add this iunder another issue, this plugin should offer some way to hide the general / main entry-point under tools. 
It sould respect permissions / groups in a way not everyone could change the base config. I don't know if this is even possible for plugins / statamic i a way, but otherwise it's use is very limited in real world usage (where you have at least two types of users. 
On the other hand: if it's not planned to implement a way to embed files & images with the plugin, it's most likely useless for most of us. 
Any way, thanks for the answers so far and thanks for your work.

**Comment by martyf** [comment]
I'm a strong believer in what TinyMCE brings to the table, but in a recent build in Statamic, have explored the Bard editor - and specifically sets within the editor - and for a Statamic project, has such incredible flexibility and power. It does miss some of TinyMCE's features, but brings others to the table (such as a configurable blueprint-based editor for complex HTML blocks) which can make authoring for clients much easier. 

If Statamic were to have an asset browser as a separately accessible URL, writing a TinyMCE plugin to utilise that URL is very straight forward. But writing a file manager outside of Statamic that does the same thing is just re-inventing the wheel. But you now have me curious to see whether there's a way to expose Statamic's file browser - then a TinyMCE plugin can simply wrap that.

I'll look at the permissions too - thanks for the heads up on that.

**Comment by michapixel** [comment]
I agree, Bard is really powerfull, especially when used as Block-editor. Tiny's advantage comes into play, when you are using different or multiple CMS in your daily life, and since it's configs have been there for a really long time now, i consider it stable. But the templating of tiny is/seems much harder to do, while bard is/seems really to be bound to statamic/laravel. 
What bard seems to lack (because of the preview feature of Statamic i guess, is the BYO-CSS feature, which i personally would love to see, but maybe it's already there.
