### ISSUE TITLE
Error loading config page

### ISSUE THREAD

**Issue by mattiusclay** [mitydigital/statamic-tinymce-cloud#4]
I'm getting an error on fresh install Statamic v3 when hitting TinyMCE Cloud menu item, pictured below:
![image](https://user-images.githubusercontent.com/18646255/184668474-c85e255a-e116-4df6-9f3a-28c28b78e9a2.png)

**Comment by martyf** [comment]
What version of PHP are you using?

**Comment by mattiusclay** [comment]
7.4

**Comment by martyf** [comment]
This add-on requires PHP 8.0 or above - upgrade your PHP version and you should be all good.

**Comment by mattiusclay** [comment]
Ah, stupid me! Thanks very much for your response

**Comment by martyf** [comment]
No stress at all :)
