### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by ottz0** [mitydigital/statamic-tinymce-cloud#6]
### Bug description

Add a default configuration option and save. When trying to save this error appears.

![Screenshot 2022-12-19 at 9 58 41 am](https://user-images.githubusercontent.com/7971800/208323859-b5bbca46-cb23-4d1b-9600-2f2f1b60eec9.png)

### Steps to reproduce

Create a new default configuration option and save

### Environment and versions

```yaml
Statamic 3.3.60 Pro
Laravel 8.83.27
PHP 8.1.9
```

**Comment by martyf** [comment]
Can you update your base Laravel install to 9 by any chance?

The Str::squish function was added with v9.

If you're just running Statamic, there should be no issues with upgrading to Laravel 9. If you have other code running, you'll need to make sure that is compatible too.

I'll update the docs to make note of Laravel 9 - even more important now with Laravel 10 just around the corner.

**Comment by ottz0** [comment]
Thanks... upgrading to Laravel 9 fixes this

**Comment by martyf** [comment]
Cool bananas - I've updated the docs to make note of this too.
