### ISSUE TITLE
YAML configuration is not enough, because it does not support funtions, e. g. custom toolbar button, js configuration is also needed

### ISSUE THREAD

**Issue by frankroc2022** [mitydigital/statamic-tinymce-cloud#7]
I want to add the character soft hyphen to the toolbar. 
More informations:
https://www.tiny.cloud/docs/tinymce/6/custom-menu-toolbar-button/

I need the addMenuButton function for example.

**Comment by martyf** [comment]
Can you please install the latest dev version:
```composer require mitydigital/statamic-tinymce-cloud:dev-main```

This now writes config to a file at `/public/vendor/statamic-tinymce-cloud/config.js` that includes a raw output of whatever you enter in to your configuration.

There is no longer any validation when saving config - it is the configurator's responsibility to ensure it is valid and correct.

Give this a whirl and let me know how you go.

Note that I am out of the office for the holidays now so will be slow to reply.

**Comment by frankroc2022** [comment]
Big THX, I will test it. Happy holidays.

**Comment by martyf** [comment]
Hey @frankroc2022 apologies for the delay - I didn't get notified that you edited your comment.

You need to re-create your config, and update your blueprints to use the new format. I'll need to work on an upgrade process.

I've just done a clean install using the dev branch, pasted a complex config, and have it running as expected.
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1491079/224842834-a6583ec3-d09f-4da5-b23d-1bcb890bcaa7.png">

**Comment by martyf** [comment]
Closed due to inactivity
