### ISSUE TITLE
add entry link

### ISSUE THREAD

**Issue by islamkh122** [mitydigital/statamic-tinymce-cloud#8]
is there way to add entry link

**Comment by martyf** [comment]
At this stage, no.

If you wanted to write a plugin for Tiny that you want to submit to this repo, that would be cool.

To be honest, we no longer use this add-on ourselves, and use Bard fields, field sets and a page builder approach for our sites. This has given us a better built-in Statamic authoring experience for use as developers, as well as our users. We are keeping this add-on open for those who do want Tiny in Statamic.
